name: "Terraform Deployment"

on:
  push:
    branches: [main]
    paths:
      - "**.tf"
      - ".github/workflows/terraform.yml"
  pull_request:
    branches: [main]
    paths:
      - "**.tf"
      - ".github/workflows/terraform.yml"
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: read
  pull-requests: write
  id-token: write # Required for OIDC authentication with AWS

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    env:
      TF_WORKSPACE: ${{ github.event.inputs.environment || 'prod' }}
      ENVIRONMENT: ${{ github.event.inputs.environment || 'prod' }}
      AWS_REGION: us-east-1
      # Terraform variables
      TF_VAR_site_name: "synepho.com"
      TF_VAR_primary_region: "us-east-1"
      TF_VAR_secondary_region: "us-west-1"
      TF_VAR_environment: "prod"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug Repository Structure
        run: |
          echo "Repository structure:"
          ls -la

          echo "Terraform variables set in environment:"
          echo "site_name: $TF_VAR_site_name"
          echo "primary_region: $TF_VAR_primary_region"
          echo "secondary_region: $TF_VAR_secondary_region"
          echo "environment: $TF_VAR_environment"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"
          terraform_wrapper: false # Important for proper plan output parsing

      # Configure AWS credentials using OIDC - single credential step
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::600424110307:role/GithubActionsOIDCTerraformRole
          aws-region: us-east-1
          role-session-name: GithubActionsOIDCSession

      # Debug step to check permissions for both regions
      - name: Debug AWS Access
        run: |
          echo "Checking AWS identity..."
          aws sts get-caller-identity

          echo "Testing primary region (us-east-1)..."
          aws s3 ls

          echo "Testing secondary region (us-west-1)..."
          aws s3 ls --region us-west-1

      - name: Create Terraform State Infrastructure
        run: |
          # 1. Check and Create S3 Bucket
          if ! aws s3api head-bucket --bucket synepho-terraform-state 2>/dev/null; then
            echo "Creating Terraform state bucket..."
            aws s3 mb s3://synepho-terraform-state --region us-east-1
            
            # Enable versioning for state recovery
            aws s3api put-bucket-versioning \
              --bucket synepho-terraform-state \
              --versioning-configuration Status=Enabled
              
            # Add encryption for security
            aws s3api put-bucket-encryption \
              --bucket synepho-terraform-state \
              --server-side-encryption-configuration '{"Rules": [{"ApplyServerSideEncryptionByDefault": {"SSEAlgorithm": "AES256"}}]}'
              
            # Block public access
            aws s3api put-public-access-block \
              --bucket synepho-terraform-state \
              --public-access-block-configuration "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"
          else
            echo "Terraform state bucket already exists."
          fi

          # 2. Check and Create DynamoDB Table
          DYNAMO_EXISTS=$(aws dynamodb describe-table --table-name terraform-locks 2>/dev/null || echo "false")
          if [ "$DYNAMO_EXISTS" = "false" ]; then
            echo "Creating DynamoDB table for state locking..."
            aws dynamodb create-table \
              --table-name terraform-locks \
              --attribute-definitions AttributeName=LockID,AttributeType=S \
              --key-schema AttributeName=LockID,KeyType=HASH \
              --billing-mode PAY_PER_REQUEST \
              --region us-east-1
              
            # Wait for the table to be created
            echo "Waiting for DynamoDB table to be active..."
            aws dynamodb wait table-exists --table-name terraform-locks
          else
            echo "DynamoDB lock table already exists."
          fi

      - name: Terraform Format Check
        id: fmt
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: |
          terraform init \
            -backend-config="bucket=synepho-terraform-state" \
            -backend-config="key=synepho-com/terraform.tfstate" \
            -backend-config="region=us-east-1" \
            -backend-config="encrypt=true" \
            -backend-config="dynamodb_table=terraform-locks"

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: |
          echo "Running plan with environment variables"
          terraform plan \
            -input=false \
            -no-color \
            -out=tfplan
        continue-on-error: true

      - name: Upload Terraform Plan Artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan
          retention-days: 7

      - name: Update PR with Plan Results
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        env:
          PLAN_EXIT_CODE: ${{ steps.plan.outcome }}
          PLAN_OUTPUT: ${{ steps.plan.outputs.stdout }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`terraform
            ${process.env.PLAN_OUTPUT}
            \`\`\`

            </details>

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
              
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        run: |
          terraform apply \
            -auto-approve \
            -input=false \
            tfplan

      - name: Output Resources
        if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        run: |
          # Handle potential missing outputs gracefully
          if terraform output -json | grep -q "website_url"; then
            echo "Website URL: $(terraform output -raw website_url)"
          else
            echo "Website URL output not found"
          fi

          if terraform output -json | grep -q "cloudfront_domain_name"; then
            echo "CloudFront Domain: $(terraform output -raw cloudfront_domain_name)"
          else
            echo "CloudFront Domain output not found"
          fi

          if terraform output -json | grep -q "primary_s3_bucket"; then
            echo "S3 Bucket: $(terraform output -raw primary_s3_bucket)"
          else
            echo "S3 Bucket output not found"
          fi

      # Optional: Invalidate CloudFront cache after deployment
      - name: Invalidate CloudFront Cache
        if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        run: |
          if terraform output -json | grep -q "cloudfront_distribution_id"; then
            DISTRIBUTION_ID=$(terraform output -raw cloudfront_distribution_id || echo "")
            if [ -n "$DISTRIBUTION_ID" ]; then
              echo "Invalidating CloudFront cache for distribution $DISTRIBUTION_ID"
              aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
            else
              echo "CloudFront distribution ID not available, skipping cache invalidation"
            fi
          else
            echo "CloudFront distribution ID output not found, skipping cache invalidation"
          fi
